In [1]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
text_data = np.array(['I love Brazil. Brazil!',
'Sweden is best',
'Germany beats both'])

In [3]:
# Create the bag of words feature matrix
count = CountVectorizer()
bag_of_words = count.fit_transform(text_data)
# Show feature matrix
bag_of_words

<3x8 sparse matrix of type '<class 'numpy.int64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [4]:
bag_of_words.toarray()

array([[0, 0, 0, 2, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 0, 0]], dtype=int64)

In [5]:
count.get_feature_names()

['beats', 'best', 'both', 'brazil', 'germany', 'is', 'love', 'sweden']

In [6]:
countbigram=CountVectorizer(ngram_range=(1,2),stop_words="english",vocabulary=['brazil'])
bg=countbigram.fit_transform(text_data)
bg.toarray()

array([[2],
       [0],
       [0]], dtype=int64)

In [8]:
countbigram.vocabulary_

{'brazil': 0}

In [ ]:
#You want a bag of words, but with words weighted by their importance to an observation.

In [9]:
doc=["One Cent, Two Cents, Old Cent, New Cent: All About Money"]

In [13]:
from sklearn.feature_extraction.text import CountVectorizer
 
lst=[
       "One Cent, Two Cents, Old Cent, New Cent: All About Money (Cat in the Hat's Learning Library",
       "Inside Your Outside: All About the Human Body (Cat in the Hat's Learning Library)",
       "Oh, The Things You Can Do That Are Good for You: All About Staying Healthy (Cat in the Hat's Learning Library)",
       "On Beyond Bugs: All About Insects (Cat in the Hat's Learning Library)",
       "There's No Place Like Space: All About Our Solar System (Cat in the Hat's Learning Library)" 
      ]

In [14]:
cv=CountVectorizer(lst)
countvector=cv.fit_transform(lst)

In [15]:
cv.vocabulary_

{'about': 0,
 'all': 1,
 'are': 2,
 'beyond': 3,
 'body': 4,
 'bugs': 5,
 'can': 6,
 'cat': 7,
 'cent': 8,
 'cents': 9,
 'do': 10,
 'for': 11,
 'good': 12,
 'hat': 13,
 'healthy': 14,
 'human': 15,
 'in': 16,
 'insects': 17,
 'inside': 18,
 'learning': 19,
 'library': 20,
 'like': 21,
 'money': 22,
 'new': 23,
 'no': 24,
 'oh': 25,
 'old': 26,
 'on': 27,
 'one': 28,
 'our': 29,
 'outside': 30,
 'place': 31,
 'solar': 32,
 'space': 33,
 'staying': 34,
 'system': 35,
 'that': 36,
 'the': 37,
 'there': 38,
 'things': 39,
 'two': 40,
 'you': 41,
 'your': 42}

In [16]:
countvector.shape

(5, 43)

In [17]:
cv = CountVectorizer(lst,stop_words=["all","in","the","is","and"])
count_vector=cv.fit_transform(cat_in_the_hat_docs)
count_vector.shape

(5, 40)

In [18]:
#Mni df
cv = CountVectorizer(lst,min_df=2)
countvector=cv.fit_transform(cat_in_the_hat_docs)
countvector

<5x8 sparse matrix of type '<class 'numpy.int64'>'
	with 40 stored elements in Compressed Sparse Row format>

In [19]:
cv.stop_words_

{'are',
 'beyond',
 'body',
 'bugs',
 'can',
 'cent',
 'cents',
 'do',
 'for',
 'good',
 'healthy',
 'human',
 'insects',
 'inside',
 'like',
 'money',
 'new',
 'no',
 'oh',
 'old',
 'on',
 'one',
 'our',
 'outside',
 'place',
 'solar',
 'space',
 'staying',
 'system',
 'that',
 'there',
 'things',
 'two',
 'you',
 'your'}

In [20]:
cv.vocabulary_ #stop words that appeared in all the titles

{'about': 0,
 'all': 1,
 'cat': 2,
 'hat': 3,
 'in': 4,
 'learning': 5,
 'library': 6,
 'the': 7}

In [21]:
#Max df
#The MAX_DF value can be an absolute value (e.g. 1, 2, 3, 4) or a value representing proportion of documents (e.g. 0.85 meaning, ignore words appeared in 85% of the documents as they are too common).
cv = CountVectorizer(lst,max_df=0.50)
count_vector=cv.fit_transform(lst)
cv.stop_words_

{'about', 'all', 'cat', 'hat', 'in', 'learning', 'library', 'the'}

In [23]:
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer

In [24]:
text_data = np.array(['I love Brazil. Brazil!',
'Sweden is best',
'Germany beats both'])

In [25]:
tfidf = TfidfVectorizer()
feature_matrix = tfidf.fit_transform(text_data)

In [26]:
feature_matrix

<3x8 sparse matrix of type '<class 'numpy.float64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [27]:
feature_matrix.toarray()

array([[0.        , 0.        , 0.        , 0.89442719, 0.        ,
        0.        , 0.4472136 , 0.        ],
       [0.        , 0.57735027, 0.        , 0.        , 0.        ,
        0.57735027, 0.        , 0.57735027],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027,
        0.        , 0.        , 0.        ]])

In [28]:
tfidf.vocabulary_

{'beats': 0,
 'best': 1,
 'both': 2,
 'brazil': 3,
 'germany': 4,
 'is': 5,
 'love': 6,
 'sweden': 7}

In [29]:
A="A system includes a processor configured to discover charging station locations within a predefined proximity to a route for which vehicle-charging is required to complete. The processor is also configured to determine a charging cost at each discovered station, including at least battery-damage resulting from a charge. The processor is further configured to present a plurality of charging stations, including the charging costs and an estimated total route time for each station. Also, the processor is configured to receive a station selection and present a route including a stop at the selected station."
B="Methods and systems for autonomous vehicle recharging or refueling are disclosed. Autonomous electric vehicles may be automatically recharged by routing the vehicles to available charging stations when not in operation, according to methods described herein. A charge level of the battery of an autonomous electric vehicle may be monitored until it reaches a recharging threshold, at which point an on-board computer may generate a predicted use profile for the vehicle. Based upon the predicted use profile, a time and location for the vehicle to recharge may be determined. In some embodiments, the vehicle may be controlled to automatically travel to a charging station, recharge the battery, and return to its starting location in order to recharge when not in use."


In [32]:
BOWA=A.split(' ')
BOWB=B.split(' ')
uniquewords=set(BOWA).union(set(BOWB))
uniquewords

{'A',
 'Also,',
 'Autonomous',
 'Based',
 'In',
 'Methods',
 'The',
 'a',
 'according',
 'also',
 'an',
 'and',
 'are',
 'at',
 'automatically',
 'autonomous',
 'available',
 'battery',
 'battery,',
 'battery-damage',
 'be',
 'by',
 'charge',
 'charge.',
 'charging',
 'complete.',
 'computer',
 'configured',
 'controlled',
 'cost',
 'costs',
 'described',
 'determine',
 'determined.',
 'disclosed.',
 'discover',
 'discovered',
 'each',
 'electric',
 'embodiments,',
 'estimated',
 'for',
 'from',
 'further',
 'generate',
 'herein.',
 'in',
 'includes',
 'including',
 'is',
 'it',
 'its',
 'least',
 'level',
 'location',
 'locations',
 'may',
 'methods',
 'monitored',
 'not',
 'of',
 'on-board',
 'operation,',
 'or',
 'order',
 'plurality',
 'point',
 'predefined',
 'predicted',
 'present',
 'processor',
 'profile',
 'profile,',
 'proximity',
 'reaches',
 'receive',
 'recharge',
 'recharged',
 'recharging',
 'refueling',
 'required',
 'resulting',
 'return',
 'route',
 'routing',
 'selec

In [33]:
noofwordsA = dict.fromkeys(uniquewords, 0)
noofwordsA

{'A': 0,
 'Also,': 0,
 'Autonomous': 0,
 'Based': 0,
 'In': 0,
 'Methods': 0,
 'The': 0,
 'a': 0,
 'according': 0,
 'also': 0,
 'an': 0,
 'and': 0,
 'are': 0,
 'at': 0,
 'automatically': 0,
 'autonomous': 0,
 'available': 0,
 'battery': 0,
 'battery,': 0,
 'battery-damage': 0,
 'be': 0,
 'by': 0,
 'charge': 0,
 'charge.': 0,
 'charging': 0,
 'complete.': 0,
 'computer': 0,
 'configured': 0,
 'controlled': 0,
 'cost': 0,
 'costs': 0,
 'described': 0,
 'determine': 0,
 'determined.': 0,
 'disclosed.': 0,
 'discover': 0,
 'discovered': 0,
 'each': 0,
 'electric': 0,
 'embodiments,': 0,
 'estimated': 0,
 'for': 0,
 'from': 0,
 'further': 0,
 'generate': 0,
 'herein.': 0,
 'in': 0,
 'includes': 0,
 'including': 0,
 'is': 0,
 'it': 0,
 'its': 0,
 'least': 0,
 'level': 0,
 'location': 0,
 'locations': 0,
 'may': 0,
 'methods': 0,
 'monitored': 0,
 'not': 0,
 'of': 0,
 'on-board': 0,
 'operation,': 0,
 'or': 0,
 'order': 0,
 'plurality': 0,
 'point': 0,
 'predefined': 0,
 'predicted': 0,
 'pre

In [55]:
for word in BOWA:
    noofwordsA[word] += 1

In [56]:
noofwordsB = dict.fromkeys(uniquewords, 0)
for word in numofwordsB:
    noofwordsB[word]+=1

In [48]:
from nltk.corpus import stopwords
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [50]:
def TF(words,BOW):
    tfdct={}
    BOWcount=len(BOW)
    for word, count in words.items():
        tfdct[word]=count/float(BOWcount)
    return tfdct

In [57]:
tfA=TF(noofwordsA, BOWA)
tfB=TF(noofwordsB,BOWB)

In [60]:
tfA
tfB

{'A': 0.008333333333333333,
 'Also,': 0.008333333333333333,
 'Autonomous': 0.008333333333333333,
 'Based': 0.008333333333333333,
 'In': 0.008333333333333333,
 'Methods': 0.008333333333333333,
 'The': 0.008333333333333333,
 'a': 0.008333333333333333,
 'according': 0.008333333333333333,
 'also': 0.008333333333333333,
 'an': 0.008333333333333333,
 'and': 0.008333333333333333,
 'are': 0.008333333333333333,
 'at': 0.008333333333333333,
 'automatically': 0.008333333333333333,
 'autonomous': 0.008333333333333333,
 'available': 0.008333333333333333,
 'battery': 0.008333333333333333,
 'battery,': 0.008333333333333333,
 'battery-damage': 0.008333333333333333,
 'be': 0.008333333333333333,
 'by': 0.008333333333333333,
 'charge': 0.008333333333333333,
 'charge.': 0.008333333333333333,
 'charging': 0.008333333333333333,
 'complete.': 0.008333333333333333,
 'computer': 0.008333333333333333,
 'configured': 0.008333333333333333,
 'controlled': 0.008333333333333333,
 'cost': 0.008333333333333333,
 'cost

In [66]:
#IDF calculation
def IDF(documents):
    import math
    N=len(documents)
    
    idfDict = dict.fromkeys(documents[0].keys(), 0)
    for document in documents:
        for word, val in document.items():
            if val > 0:
                idfDict[word] += 1
    
    for word, val in idfDict.items():
        idfDict[word] = math.log(N / float(val))
    return idfDict

In [67]:
idfs = IDF([noofwordsA, noofwordsB])

In [68]:
idfs

{'A': 0.0,
 'Also,': 0.0,
 'Autonomous': 0.6931471805599453,
 'Based': 0.6931471805599453,
 'In': 0.6931471805599453,
 'Methods': 0.6931471805599453,
 'The': 0.0,
 'a': 0.0,
 'according': 0.6931471805599453,
 'also': 0.0,
 'an': 0.0,
 'and': 0.0,
 'are': 0.6931471805599453,
 'at': 0.0,
 'automatically': 0.6931471805599453,
 'autonomous': 0.6931471805599453,
 'available': 0.6931471805599453,
 'battery': 0.6931471805599453,
 'battery,': 0.6931471805599453,
 'battery-damage': 0.0,
 'be': 0.6931471805599453,
 'by': 0.6931471805599453,
 'charge': 0.6931471805599453,
 'charge.': 0.0,
 'charging': 0.0,
 'complete.': 0.0,
 'computer': 0.6931471805599453,
 'configured': 0.0,
 'controlled': 0.6931471805599453,
 'cost': 0.0,
 'costs': 0.0,
 'described': 0.6931471805599453,
 'determine': 0.0,
 'determined.': 0.6931471805599453,
 'disclosed.': 0.6931471805599453,
 'discover': 0.0,
 'discovered': 0.0,
 'each': 0.0,
 'electric': 0.6931471805599453,
 'embodiments,': 0.6931471805599453,
 'estimated': 0

In [46]:
#list(feature_names)
#list(dense)

In [69]:
def TFIDF(tfBagOfWords, idfs):
    tfidf = {}
    for word, val in tfBagOfWords.items():
        tfidf[word] = val * idfs[word]
    return tfidf

In [71]:
tfidfA = TFIDF(tfA, idfs)
tfidfB = TFIDF(tfB, idfs)
df = pd.DataFrame([tfidfA, tfidfB])
df

station  station,  plurality   of  also  costs  computer  charge.  the  \
0      0.0       0.0        0.0  0.0   0.0    0.0  0.000000      0.0  0.0   
1      0.0       0.0        0.0  0.0   0.0    0.0  0.005776      0.0  0.0   

   on-board  ...    travel      upon        in  stop  which  location  and  \
0  0.000000  ...  0.000000  0.000000  0.000000   0.0    0.0  0.000000  0.0   
1  0.005776  ...  0.005776  0.005776  0.005776   0.0    0.0  0.005776  0.0   

      point      use.   Methods  
0  0.000000  0.000000  0.000000  
1  0.005776  0.005776  0.005776  

[2 rows x 114 columns]

In [72]:
#Sci kit learn TF IDF implementation
import pandas as pd
vectorizer = TfidfVectorizer()
vectors = vectorizer.fit_transform([A, B])
feature_names = vectorizer.get_feature_names()
dense = vectors.todense()
denselist = dense.tolist()
df = pd.DataFrame(denselist, columns=feature_names)
df

according      also        an       and       are        at  automatically  \
0   0.000000  0.152565  0.054276  0.108552  0.000000  0.162827       0.000000   
1   0.064347  0.000000  0.091566  0.137349  0.064347  0.045783       0.128693   

   autonomous  available     based  ...     total    travel     until  \
0     0.00000   0.000000  0.000000  ...  0.076283  0.000000  0.000000   
1     0.19304   0.064347  0.064347  ...  0.000000  0.064347  0.064347   

       upon      use   vehicle  vehicles      when     which    within  
0  0.000000  0.00000  0.054276  0.000000  0.000000  0.054276  0.076283  
1  0.064347  0.19304  0.228916  0.128693  0.128693  0.045783  0.000000  

[2 rows x 99 columns]